### ISSUE TITLE
Install w/ yeoman angular stack?

### ISSUE THREAD

**Issue by chadobado** [taras/grunt-deployd#1]
Am trying to get this to work with the yeoman angular scaffolding but am not having any luck... any insights?

Thanks a lot in advance,

Chad

**Comment by chadobado** [comment]
Made some good progress, but whenever I hit the dashboard the system tanks... grunt-autoprefixer is in node_modules and appears intact.

Error loading module node_modules/grunt-autoprefixer
Error: Cannot find module '/Users/chad/work/f2/node_modules/grunt-autoprefixer'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at /Users/chad/work/f2/node_modules/deployd/lib/type-loader.js:39:27
    at process._tickDomainCallback (node.js:459:13)

**Comment by chadobado** [comment]
Patching to this appeared to resolve this problem: 

https://github.com/deployd/deployd/pull/240/files

**Comment by chadobado** [comment]
Awesome, got it working after hacking around the gruntfile and digging deeper into the grunt-connect-proxy package... wasn't able to figure out proxying :9000/dashboards -> :7777/dashboards though.

Will add a repo tomorrow with the example... thanks a lot for this package

**Comment by taras** [comment]
@chadobado It looks like I missed your messages yesterday. I'm glad you got it figured out. 

I also wasn't able to figure out how to get the /dashboard proxy working. I think it would require some change on Depoyd.app.

Look forward to the example.

**Comment by chadobado** [comment]
@taras Yes, I was playing around with some socket.io proxying and think I see how to add support using grunt-connect-proxy for the dashboard, will play with that when I get a chance.

In the mean time I cobbled together a yeoman scaffold based on brian's generator-angular.  It's really hacked (I needed to get going quickly) but works.

https://github.com/chadobado/generator-angular

As a note, considering the deployd node_module uses a broken type-loader.js you need to run an additional command to update after the dependencies have been added:

yo angular-deployd
yo angular-deployd:deployd

The gruntfile is located here for reference: 

https://github.com/chadobado/generator-angular/blob/master/templates/common/Gruntfile.js

If you've never used Yeoman these steps should get you going:

npm install yeoman -g
npm install generator-angular -g  # generator-angular-deployd currently runs several generator-angular tasks
git clone https://github.com/chadobado/generator-angular generator-angular-deployd
cd generator-angular
npm install
npm link
cd ..
mkdir testproject
cd testproject
yo angular-deployd  # complete steps
yo angular-deployd:deployd  # accept overwrite request
grunt server

I'll clean this up later and probably create a separate scaffold for deployd once I get more comfortable with Yeoman updates to the gruntfile.

**Comment by taras** [comment]
@chadobado I'm familiar with Yeoman. 

Is type-loader.js still a problem because there were some efforts by Deployd to fix it?

**Comment by chadobado** [comment]
@taras Ah thanks looks like I was inadvertently using 6.10 and not 6.11

**Comment by chadobado** [comment]
@taras I updated to 6.11 but still seeing some errors here.. any ideas?  thanks in advance..

On loading dashboard:

```
Waiting...
Error loading module node_modules/grunt-autoprefixer
Error: Cannot find module '/Users/chad/Documents/Dev/test/node_modules/grunt-autoprefixer'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at /Users/chad/Documents/Dev/test/node_modules/deployd/lib/type-loader.js:39:27
    at process._tickDomainCallback (node.js:459:13)
```

updating ./node_modules/deployd/lib/type-loader.js as we discussed above seems to fix.

However, the bigger problem I'm seeing - all dpd.js requests look for /collection instead of /api/collection...  

Identical configuration works with 0.6.10, but not with 0.6.11... Did something change between the versions?

I'm requesting dpd via as mentioned in the docs: 

```
<script type="text/javascript" src="/api/dpd.js"></script>
```

Thanks a lot for your help

**Comment by chadobado** [comment]
I do notice the same issue when cloning this repo...

Added to index.html

```
<script>
        dpd.widgets.post({name:"testing"},function(r,e) {
            console.log(r)
        })
    </script>
```

resulting in: 

> POST http://localhost:9000/widgets 404 (Not Found)

**Comment by chadobado** [comment]
Looks like the alternative invocation works:

```
dpd('api/widgets').post({name:"hi"},function(r,e) {
            console.log(r)
        })
```

**Comment by taras** [comment]
I just wanted to let you know that I'm going to look at this later today.

**Comment by chadobado** [comment]
Hey @taras , curious if you ever had a chance to take a look... I was able to use the above invocation but now that i've tried to deploy to heroku I seem to have a whole new host of problems.  Have you been able to successfully deploy this?

Thanks

**Comment by taras** [comment]
@chadobado Hi, I'm sorry I never did look into it. I stopped working with Deployd so it kind off fell off my priority list. Sorry about that. I never did push it to production.

**Comment by chadobado** [comment]
@taras Not a problem, thanks for the reply.  What did you switch to btw?  Anything worth looking at?

**Comment by taras** [comment]
I created http://embersherpa.com/ If you have any interest in Ember, you might want to checkout my article about doing CRUD without Ember Data. 

I'm building a static generator called Embersmith ( a fork of Wintersmith ). 

It's going to have a few really cool features that are helpful in early development.
